### ISSUE TITLE
connectAndSetUp() callback is never called using noble > 1.8.1

### ISSUE THREAD

**Issue by DurandA** [noble/noble#773] opened 2018-03-18 00:25 UTC
I recently experienced problems on Linux with _noble@1.9.0_ (using _noble-device@1.4.1_) as `onDiscover()` succeed while `connectAndSetUp()` callback is never fired. I was surprised as I had a setup previously working with the same device (a [Nordic Thingy:52](https://www.nordicsemi.com/eng/Products/Nordic-Thingy-52)) using the same Bluetooth controller (Intel Bluetooth). I tried with another Bluetooth controller (Cambridge Silicon Radio USB dongle) with the same problems. I also tried with different kernel 4.8 and 4.11. I finally tried on a [C.H.I.P.](https://getchip.com/pages/chip) using both the integrated Bluetooth controller and the USB dongle, yielding the same result. After further investigation, `discoverServicesAndCharacteristics()` callback is never triggered.

However, when downgrading _noble_ to 1.8.1, `connectAndSetUp()` works as expected.

Steps to reproduce:
```
function onDiscover(thingy) {
  console.log('Discovered!');

  thingy.on('disconnect', function() {
    console.log('Disconnected!');
  });

  thingy.connectAndSetUp(function(error) {
    console.log('Connected! ' + error);
  });
}

Thingy.discover(onDiscover);
```
This output:
> Discovered!

**Comment by sandeepmistry** [comment] 2018-03-18 23:36
Duplicate of #765 which is fixed by #769.

**Closed by sandeepmistry** 2018-03-18 23:36 UTC
Labels: duplicate
